### ISSUE TITLE
Rendering issue with https://valdrinkoshi.github.io/virtual-list/demo/contacts/lit-html/

### ISSUE THREAD

**Issue by kenchris** [valdrinkoshi/virtual-list#39]
Click on one of the items (in Chrome) and change the text with the keyboard... then scroll, like moving the scrollbar with the mouse - lots of rendering artifacts. At one point I had the same item stay visible always while scrolling

**Comment by kenchris** [comment]
![screenshot 2018-04-30 at 14 31 21](https://user-images.githubusercontent.com/1101339/39427197-2ed69812-4c83-11e8-9d1f-2d2135a32707.png)
![screenshot 2018-04-30 at 14 31 16](https://user-images.githubusercontent.com/1101339/39427198-2f12b356-4c83-11e8-8c4f-2ce71e75f178.png)

**Comment by valdrinkoshi** [comment]
This is caused by the fact that `[contenteditable]` changes the dom, and the startNode/endNode of the lit-html directive get disconnected.
This can be reproduced also with the `repeat()` directive, I wonder if this should be considered a user error or something that lit-html should handle - opened an issue here https://github.com/Polymer/lit-html/issues/316
